export default {
    install: 'https://bluebubbles.app/install',
    docs: 'https://docs.bluebubbles.app',
    troubleshooting: 'https://docs.bluebubbles.app/server/troubleshooting-guides/trouble-shooting-guides-overview',
    faq: 'https://bluebubbles.app/faq',
    source_code: 'https://github.com/BlueBubblesApp',
    donate: 'https://bluebubbles.app/donate',
    sponsor: 'https://github.com/sponsors/BlueBubblesApp',
    report_bug: 'https://github.com/BlueBubblesApp/bluebubbles-app/issues',
    request_feature: 'https://github.com/BlueBubblesApp/bluebubbles-app/issues',
    phone_registration: 'https://docs.bluebubbles.app/server/advanced/registering-a-phone-number-with-your-imessage-account',
    no_notifications: 'https://docs.bluebubbles.app/server/troubleshooting-guides/not-receiving-notifications-or-url-changes-on-android',
    mac_virtualization: 'https://docs.bluebubbles.app/server/advanced/macos-virtualization',
    private_api: 'https://docs.bluebubbles.app/private-api/installation',
    github_app_release: 'https://github.com/bluebubblesapp/bluebubbles-app/releases',
    github_server_release: 'https://github.com/bluebubblesapp/bluebubbles-server/releases',
    play_store: 'https://play.google.com/store/apps/details?id=com.bluebubbles.messaging',
    microsoft_store: 'https://apps.microsoft.com/store/detail/9P3XF8KJ0LSM',
    tailscale: 'https://docs.bluebubbles.app/server/advanced/byo-proxy-service-guides/tailscale-vpn-setup',
    docker_osx: 'https://github.com/sickcodes/Docker-OSX',
    logged_out_of_imessage: 'https://www.reddit.com/r/hackintosh/comments/nj8yeu/imessage_problem_instantly_logged_out/'
}